language: node_js
cache: npm
node_js:
  - 6
  - 8
  - 10
  - 11
  - node

before_deploy: npm run prepublishOnly
deploy:
  provider: npm
  email: andreas@stassi.net
  api_key:
    secure: hOEAb5XrJxEFjCMEEROH5CouU6gdhd0kq/jihcKdXxE4Cvzq5W4Dx4Vkxxn+OysD6zdLEkY7awMlEpXRdRdyKWaD+5RO3K/WBmbkIA3b5mEvzaR1x2wOF36oFQ9uTvsmsrL4bErB+Uylrt6/rDUqzNgLKhNnc2mx+6rz9YBsw10JO0Tmi20FO0NXKEZRmPb7Us/eijVURNsTXrH2WG5rtUYnh8mKJEs27tGfDXoy446dA1IuO89xRottSMf9TQ3gcxVfn4dXNr8kC10oA4rUJjf90UTX77d3Afucc4Q2typk0n4iV/3vTvgXK7f/423/OwfGGVoDyG+21EgZITnqzC0an42v62mM/f57UgzDw8aBVA/23/pRWXHa8nR64qTaYqHXTLVRHW3gp55UhsTsOFshum7hTerBjEGlPFMqlXc2XKIcjJDBO0t4fS7RrsYaEJb9weqyavzDDQugt/98c0k0jKIdWFNpXSNZTQHJMEPiXRmWEKdV/6g9Jdo9mJmlOkAmNPZXQXZmvnVMwkTea6H+U3rMzlYBzRFSjEO2oJvR88EC2AQI2qOTOZeG4MTsDwTfb88gIds3FX2lTUNL095tuThqlUZukiG/r37dMkz8wqN4qpDoXK0wJ3Nfcx4YzQXae6qVdyhgjK7bH3PLidfMXbu/5y/h2ZxpQVsIeyU=
  skip_cleanup: true
  on:
    node: 10
